<a href="https://colab.research.google.com/github/tim108108/Python_Code/blob/master/Vacuum_Cleaner_Agent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [264]:
import numpy as np

class env:

  def intit(length=4 ,width=4):   #預設4x4
    world = np.zeros((length, width))
    for i in range(world.shape[0]):
      for j in range(world.shape[1]):
        world[i][j] = np.random.randint(2)
    return world 

class agent:

  def scan(world):
    return np.argwhere(world>0)
  def act(world, dust_list):
    for i in dust_list:
      world[i[0],i[1]]=0
      print("===================")
      print(world)
      print("clean",i)



mars = env.intit()        #生成環境，預設4x4
print("What the environment like:\n",mars,"\n")

print("list of dust")
dirty = agent.scan(mars)    #找出髒污
print(dirty)           #列出位置
agent.act(mars, dirty)     #執行動作

What the environment like:
 [[1. 1. 0. 1.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [0. 1. 1. 1.]] 

list of dust
[[0 0]
 [0 1]
 [0 3]
 [1 0]
 [1 1]
 [2 0]
 [2 1]
 [3 1]
 [3 2]
 [3 3]]
[[0. 1. 0. 1.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [0. 1. 1. 1.]]
clean [0 0]
[[0. 0. 0. 1.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [0. 1. 1. 1.]]
clean [0 1]
[[0. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [0. 1. 1. 1.]]
clean [0 3]
[[0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 1. 0. 0.]
 [0. 1. 1. 1.]]
clean [1 0]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 0. 0.]
 [0. 1. 1. 1.]]
clean [1 1]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 1. 1.]]
clean [2 0]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 1. 1.]]
clean [2 1]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 1.]]
clean [3 1]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 1.]]
clean [3 2]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
clean [3 3]
